### ISSUE TITLE
canton.osm on task manager cannot be opened

### ISSUE THREAD

**Issue by talllguy** [osmlab/bmorebuildings#13]
Getting the following error:
![error](https://www.evernote.com/shard/s5/sh/3c8fe469-0b80-4f2e-8e76-d8823b1f4633/a6058a03425f4953b57e80c63ceaa74e/deep/0/Error-and-Java-OpenStreetMap-Editor.png)

**Comment by mpetroff** [comment]
See #14. Deleting the specific way fixes things; worst case, we lose one building.

**Comment by mpetroff** [comment]
Done.
