### ISSUE TITLE
villages_of_homeland.osm has error

### ISSUE THREAD

**Issue by talllguy** [osmlab/bmorebuildings#14]

**Comment by mpetroff** [comment]
There are a number of files that seem to have errors from Osmosis splitting the data. The easy fix is to open the OSM file in a text editor and delete the way that JOSM complains about. Also, I uploaded this file.

**Comment by mpetroff** [comment]
It turns out that there's a flag for Osmosis to include the complete building when it's on the border, which I didn't use. I just reran the split with the flag, so all the files should now be valid; there had been dozens of files that wouldn't open in JOSM.

**Comment by talllguy** [comment]
@mpetroff That sounds like a great solution. Nice!
