### ISSUE TITLE
Street type of "Parkway" is missing

### ISSUE THREAD

**Issue by roadgeek** [osmlab/bmorebuildings#8]
East/West Northern is missing Parkway, along with Gwynns Falls and maybe others

**Comment by mpetroff** [comment]
Complete list of parkways:

```
Chinquapin Parkway
East Northern Parkway
East University Parkway
Eastern Parkway
Green Meadow Parkway
Gwynns Falls Parkway
Perring Parkway
Tioga Parkway
West Northern Parkway
West University Parkway
Wildwood Parkway
Wyman Parkway
```

Thanks for pointing this out. Unfortunately, most of the data was uploaded yesterday, and 1853 addresses were uploaded that are missing "Parkway" and now need to be fixed.

**Comment by mpetroff** [comment]
I just finished fixing everything that was already uploaded as well as the data that will be manually uploaded.

**Comment by talllguy** [comment]
Very strange, somehow I either missed that in the data or they were coded differently https://github.com/osmlab/bmorebuildings/blob/master/address-building/ogr2osm-translations/bc-address.py#L34-L39
